// ── Dummy data ────────────────────────────────────────────────────────────────
export const DUMMY = {
    inputText:
      "Wah aya khti! Ce soir on va directement à Bab El Oued et après direction la plage, ndirou la fête. Et ftor, wesh rak?",
    ihl: 42,
    sentiment: { label: "positif", score: 64 },
    dominante: "dominante arabe",
    intensite: "intensité forte",
    emotionScore: 54,
    langues: [
      { name: "Algérien", pct: 63, color: "#10b981", flag: "🇩🇿" },
      { name: "Français", pct: 37, color: "#f97316", flag: "🇫🇷" },
    ],
    tokens: [
      { word: "Wah", lang: "ar" , highlight: true},
      { word: " aya", lang: "ar", highlight: true },
      { word: " khti!", lang: "ar", highlight: true },
      { word: " Ce", lang: "fr", highlight: true },
      { word: " soir", lang: "fr", highlight: true },
      { word: " on", lang: "fr", highlight: true   },
      { word: " va", lang: "fr", highlight: true },
      { word: " directement", lang: "fr", highlight: true },
      { word: " à", lang: "fr", highlight: true },
      { word: " Bab", lang: "ar", highlight: true },
      { word: " El", lang: "ar", highlight: true },
      { word: " Oued", lang: "ar", highlight: true },
      { word: " et", lang: "fr", highlight: true },
      { word: " après", lang: "fr", highlight: true },
      { word: " direction", lang: "fr", highlight: true },
      { word: " la", lang: "fr", highlight: true },
      { word: " plage,", lang: "fr", highlight: true },
      { word: " ndirou", lang: "ar", highlight: true },
      { word: " la", lang: "fr", highlight: true },
      { word: " fête.", lang: "fr", highlight: true },
      { word: " Et", lang: "fr", highlight: true },
      { word: " fotrr,", lang: "ar", highlight: true },
      { word: " wesh", lang: "ar", highlight: true },
      { word: " rak?", lang: "ar", highlight: true },
    ],
  };